import pyqtgraph as pg
from PyQt5 import QtCore, QtWidgets

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super(MainWindow, self).__init__()
        self.setWindowTitle("Xe can bang vip pro")
        self.resize(1080, 640)

    def GUI_init(self):
        self.widget = QtWidgets.QWidget(self)
        self.setCentralWidget(self.widget)
        self.main_layout = QtWidgets.QGridLayout()
        self.widget.setLayout(self.main_layout)

        # Main layout
        self.serial_layout = QtWidgets.QGridLayout()
        self.plot_layout = QtWidgets.QVBoxLayout()
        self.tuning_layout = QtWidgets.QVBoxLayout()
        self.main_layout.addLayout(self.serial_layout, 0, 0, 1, 1)
        self.main_layout.addLayout(self.plot_layout, 0, 1, -1, -1)
        self.main_layout.addLayout(self.tuning_layout, 1, 0, -1, 1)
        self.main_layout.setColumnStretch(0, 3)
        self.main_layout.setColumnStretch(1, 7)

        # Serial layout
        self.port_label = QtWidgets.QLabel('Port: ')
        self.port_list = QtWidgets.QComboBox()
        self.port_label.setBuddy(self.port_list)
        self.baud_label = QtWidgets.QLabel('Baudrate: ')
        self.baudrate_list = QtWidgets.QComboBox()
        self.baud_label.setBuddy(self.baudrate_list)
        self.connect_btn = QtWidgets.QPushButton(text='Connect', checkable=True)
        self.serial_layout.addWidget(self.port_label, 0, 0)
        self.serial_layout.addWidget(self.port_list, 0, 1, 1, 3)
        self.serial_layout.addWidget(self.baud_label, 1, 0)
        self.serial_layout.addWidget(self.baudrate_list, 1, 1, 1, 3)
        self.serial_layout.addWidget(self.connect_btn, 2, 0, -1, -1)

        # Tab Layout
        self.tabs = QtWidgets.QTabWidget()
        self.sensor_tab = QtWidgets.QWidget()
        self.motor_tab = QtWidgets.QWidget()
        self.pid_tab = QtWidgets.QWidget()
        self.debug_tab = QtWidgets.QWidget()
        self.tabs.addTab(self.sensor_tab, "Sensor")
        self.tabs.addTab(self.motor_tab, "Motor")
        self.tabs.addTab(self.pid_tab, "PID")
        self.tabs.addTab(self.debug_tab, "Debug")

        self.sensor_tab.layout = QtWidgets.QVBoxLayout()
        self.imu = QtWidgets.QGroupBox('IMU')
        self.imu_form = QtWidgets.QFormLayout()
        self.roll = QtWidgets.QLineEdit(readOnly=True)
        self.pitch = QtWidgets.QLineEdit(readOnly=True)
        self.yaw = QtWidgets.QLineEdit(readOnly=True)
        self.imu_form.addRow('Roll: ', self.roll)
        self.imu_form.addRow('Pitch: ', self.pitch)
        self.imu_form.addRow('Yaw: ', self.yaw)
        self.imu.setLayout(self.imu_form)
        # self.gyro = QtWidgets.QGroupBox('Gyro offset')
        # self.gyro_form = QtWidgets.QFormLayout()
        # self.gyro_form.addRow(QtWidgets.QLabel('X: '), QtWidgets.QLineEdit(readOnly=True))
        # self.gyro_form.addRow(QtWidgets.QLabel('Y: '), QtWidgets.QLineEdit(readOnly=True))
        # self.gyro_form.addRow(QtWidgets.QLabel('Z: '), QtWidgets.QLineEdit(readOnly=True))
        # self.gyro.setLayout(self.gyro_form)
        # self.accel = QtWidgets.QGroupBox('Accel offset')
        # self.accel_form = QtWidgets.QFormLayout()
        # self.accel_form.addRow(QtWidgets.QLabel('X: '), QtWidgets.QLineEdit(readOnly=True))
        # self.accel_form.addRow(QtWidgets.QLabel('Y: '), QtWidgets.QLineEdit(readOnly=True))
        # self.accel_form.addRow(QtWidgets.QLabel('Z: '), QtWidgets.QLineEdit(readOnly=True))
        # self.accel.setLayout(self.accel_form)
        # self.mag = QtWidgets.QGroupBox('Mag offset')
        # self.mag_form = QtWidgets.QFormLayout()
        # self.mag_form.addRow(QtWidgets.QLabel('X: '), QtWidgets.QLineEdit(readOnly=True))
        # self.mag_form.addRow(QtWidgets.QLabel('Y: '), QtWidgets.QLineEdit(readOnly=True))
        # self.mag_form.addRow(QtWidgets.QLabel('Z: '), QtWidgets.QLineEdit(readOnly=True))
        # self.mag.setLayout(self.mag_form)
        # self.ahrs = QtWidgets.QGroupBox('AHRS')
        # self.ahrs_form = QtWidgets.QFormLayout()
        # self.ahrs_form.addRow(QtWidgets.QLabel("Temperature: "), QtWidgets.QLineEdit(readOnly=True))
        # self.ahrs_form.addRow(QtWidgets.QLabel("Pressure: "), QtWidgets.QLineEdit(readOnly=True))
        # self.ahrs_form.addRow(QtWidgets.QLabel("Altitude: "), QtWidgets.QLineEdit(readOnly=True))
        # self.ahrs.setLayout(self.ahrs_form)
        self.sensor_tab.layout.addWidget(self.imu)
        # self.sensor_tab.layout.addWidget(self.gyro)
        # self.sensor_tab.layout.addWidget(self.accel)
        # self.sensor_tab.layout.addWidget(self.mag)
        # self.sensor_tab.layout.addWidget(self.ahrs)

        self.motor_tab.layout = QtWidgets.QVBoxLayout()
        self.encoder = QtWidgets.QGroupBox('Speed')
        self.encoder_form = QtWidgets.QFormLayout()
        self.encoder_form.addRow(QtWidgets.QLabel("M0: "), QtWidgets.QLineEdit(readOnly=True))
        self.encoder_form.addRow(QtWidgets.QLabel("M1: "), QtWidgets.QLineEdit(readOnly=True))
        self.encoder_form.addRow(QtWidgets.QLabel("M2: "), QtWidgets.QLineEdit(readOnly=True))
        self.encoder_form.addRow(QtWidgets.QLabel("M3: "), QtWidgets.QLineEdit(readOnly=True))
        self.encoder.setLayout(self.encoder_form)
        self.pwm = QtWidgets.QGroupBox('PWM')
        self.pwm_form = QtWidgets.QFormLayout()
        self.slider0 = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.slider0.setMinimum(-1000)
        self.slider0.setMaximum(1000)
        self.slider0.setValue(0)
        self.slider1 = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.slider1.setMinimum(-1000)
        self.slider1.setMaximum(1000)
        self.slider1.setValue(0)
        self.slider2 = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.slider2.setMinimum(-1000)
        self.slider2.setMaximum(1000)
        self.slider2.setValue(0)
        self.slider3 = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.slider3.setMinimum(-1000)
        self.slider3.setMaximum(1000)
        self.slider3.setValue(0)
        self.pwm_form.addRow(QtWidgets.QLabel("M0: "), self.slider0)
        self.pwm_form.addRow(QtWidgets.QLabel("M1: "), self.slider1)
        self.pwm_form.addRow(QtWidgets.QLabel("M2: "), self.slider2)
        self.pwm_form.addRow(QtWidgets.QLabel("M3: "), self.slider3)
        self.pwm.setLayout(self.pwm_form)
        self.motor_tab.layout.addWidget(self.encoder)
        self.motor_tab.layout.addWidget(self.pwm)

        self.pid_tab.layout = QtWidgets.QVBoxLayout()
        self.pid1 = QtWidgets.QGroupBox('Tilt PID')
        self.pid1_form = QtWidgets.QFormLayout()
        self.pid1_form.addRow('Kp: ', QtWidgets.QDoubleSpinBox())
        self.pid1_form.addRow('Ki: ', QtWidgets.QDoubleSpinBox())
        self.pid1_form.addRow('Kd: ', QtWidgets.QDoubleSpinBox())
        self.pid1.setLayout(self.pid1_form)
        self.pid2 = QtWidgets.QGroupBox('Velocity PID')
        self.pid2_form = QtWidgets.QFormLayout()
        self.pid2_form.addRow('Kp: ', QtWidgets.QDoubleSpinBox())
        self.pid2_form.addRow('Ki: ', QtWidgets.QDoubleSpinBox())
        self.pid2_form.addRow('Kd: ', QtWidgets.QDoubleSpinBox())
        self.pid2.setLayout(self.pid2_form)
        self.save_btn = QtWidgets.QPushButton(text='Save')
        self.load_btn = QtWidgets.QPushButton(text='Load')
        self.pid_tab.layout.addWidget(self.pid1)
        self.pid_tab.layout.addWidget(self.pid2)
        self.pid_tab.layout.addWidget(self.save_btn)
        self.pid_tab.layout.addWidget(self.load_btn)

        self.debug_tab.layout = QtWidgets.QVBoxLayout()
        self.output_text = QtWidgets.QTextEdit(readOnly=True)
        self.message_line = QtWidgets.QLineEdit()
        self.send_btn = QtWidgets.QPushButton(text='Send')
        self.debug_tab.layout.addWidget(self.output_text)
        self.debug_tab.layout.addWidget(self.message_line)
        self.debug_tab.layout.addWidget(self.send_btn)

        self.sensor_tab.setLayout(self.sensor_tab.layout)
        self.motor_tab.setLayout(self.motor_tab.layout)
        self.pid_tab.setLayout(self.pid_tab.layout)
        self.debug_tab.setLayout(self.debug_tab.layout)
        self.tuning_layout.addWidget(self.tabs)

        self.plot = pg.GraphicsLayoutWidget()
        self.plot.setBackground('w')
        self.p0 = self.plot.addPlot(0, 0, title='Gyro X')
        self.p0.showGrid(x=True, y=True)
        # self.p0.setRange(yRange=[-10,10])
        self.p1 = self.plot.addPlot(0, 1, title='Gyro Y')
        self.p1.showGrid(x=True, y=True)
        # self.p1.setRange(yRange=[-10,10])
        self.p2 = self.plot.addPlot(0, 2, title='Gyro Z')
        self.p2.showGrid(x=True, y=True)
        # self.p2.setRange(yRange=[-10,10])
        self.p3 = self.plot.addPlot(1, 0, title='Accel X')
        self.p3.showGrid(x=True, y=True)
        # self.p3.setRange(yRange=[-10,10])
        self.p4 = self.plot.addPlot(1, 1, title='Accel Y')
        self.p4.showGrid(x=True, y=True)
        # self.p4.setRange(yRange=[-10,10])
        self.p5 = self.plot.addPlot(1, 2, title='Accel Z')
        self.p5.showGrid(x=True, y=True)
        # self.p5.setRange(yRange=[-10,10])
        self.p6 = self.plot.addPlot(2, 0, title='Mag X')
        self.p6.showGrid(x=True, y=True)
        # self.p6.setRange(yRange=[-10,10])
        self.p7 = self.plot.addPlot(2, 1, title='Mag Y')
        self.p7.showGrid(x=True, y=True)
        # self.p7.setRange(yRange=[-10,10])
        self.p8 = self.plot.addPlot(2, 2, title='Mag Z')
        self.p8.showGrid(x=True, y=True)
        # self.p8.setRange(yRange=[-10,10])
        self.curve0 = self.p0.plot(pen=pg.mkPen('r', width=2))
        self.curve1 = self.p1.plot(pen=pg.mkPen('g', width=2))
        self.curve2 = self.p2.plot(pen=pg.mkPen('b', width=2))
        self.curve3 = self.p3.plot(pen=pg.mkPen('r', width=2))
        self.curve4 = self.p4.plot(pen=pg.mkPen('g', width=2))
        self.curve5 = self.p5.plot(pen=pg.mkPen('b', width=2))
        self.curve6 = self.p6.plot(pen=pg.mkPen('r', width=2))
        self.curve7 = self.p7.plot(pen=pg.mkPen('g', width=2))
        self.curve8 = self.p8.plot(pen=pg.mkPen('b', width=2))
        self.plot_layout.addWidget(self.plot)

    def write_form(self, form, itemAt, value):
        # Update QLineEdit's text, not QLabel's
        item = form.itemAt(itemAt * 2 + 1).widget()
        if isinstance(item, QtWidgets.QLineEdit):
            item.setText(str(value))
        elif isinstance(item, QtWidgets.QDoubleSpinBox):
            item.setValue(float(value))

    def read_form(self, form, itemAt):
        item = form.itemAt(itemAt * 2 + 1).widget()
        if isinstance(item, QtWidgets.QDoubleSpinBox):
            return item.value()
            